apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: information
  labels:
    app.kubernetes.io/name: information-service
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: information-service
  template:
    metadata:
      labels:
        app.kubernetes.io/name: information-service
    spec:
      containers:
      - name: app
        image: ghcr.io/twin-te/information-service:master
        env:
        - name: PG_HOST
          value: postgresql-proxy
        - name: PG_DATABASE
          valueFrom:
            secretKeyRef:
              name: information-postgres-credentials
              key: database
        - name: PG_USERNAME
          valueFrom:
            secretKeyRef:
              name: information-postgres-credentials
              key: user
        - name: PG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: information-postgres-credentials
              key: password
        ports:
        - name: grpc
          containerPort: 50051
        readinessProbe:
          tcpSocket:
            port: 50051
