apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: information
  labels:
    app.kubernetes.io/name: information-service
spec:
  selector:
    app.kubernetes.io/name: information-service
  ports:
  - name: grpc
    port: 50051